language: node_js
node_js:
- '8'

script:
- yarn test:cov
- yarn build

deploy:
  provider: npm
  email: rolandjitsu@gmail.com
  api_key:
    secure: fAl3728T6duMHcVl1rUW1xu+yuC02ix+66Xb8T94cVhGpMMXhRgh4pkhI8tmSPlF2bIqLNge/BjmKPuHzln3+pGfWNqqUsS94UPV3si7UVMsIFOBhe8422WBOIlN7Qy63z2wgKn1IjRGTP8m+hh49jeKen2/Bm7M2E6hCKwzBqinPDi/cMyQ6Gw2BNKPtxconbQRxXvb6jl7oFH8T8/xmH53yrSk+qhQRjBKZ4TkQvu1ValVeMSARyvrL4DCnwuqGz1mjImiaS4uFuGJvp1IT4jSjjiIwLOxDtvVGFv+P8whN2QN+6EQ+RpRPf5NUeit+xSfMSqwSqgmOF4sGEi/PrF/j/gGTI3npFNt3ihVdTkqf5YcqulIb12afBHoCTp0Ds0UuUyh5u9oJqWXus4DdTlwJ3EWSKMJKa02tRvjL7u055oyoTMlVbAisf4EgO7GiixGiwZTcwLhxpOzlrp2bsnnCrEsiIN9Az2s28VS56Lo8YIWDihQAzXKQjdphQATU2LUdNxMeieaNbaYQw/wLaTABUMs7+jECYE5uTnm0oRv126E5jIJZjUVZf3RB6DYn3So54vkDy6shPzW0BIhJhvEYkdHWje3fX8SXiU0B7Os5kQi+6zcS0zitxVZ48GmfEAx+TAxczEJjt1raIWmIBrb6MwXzM99SXRcyRSHa/c=
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: change
